### ISSUE TITLE
之前的评论没了

### ISSUE THREAD

**Issue by CyrusYip** [earfanfan/yuanfan#2]
打开 https://yuanfan.rbind.io/posts/qianbo/ 看了下，发现之前评论都没了。旧链接是有评论的 https://yuanfan.vercel.app/posts/qianbo/ 。

<img width="832" alt="image" src="https://user-images.githubusercontent.com/60951091/188045031-4f0944bc-d887-458b-b22d-4d501cb23f17.png">

**Comment by earfanfan** [comment]
我知道，原来的博客和底下的评论就当作是被我沉入海底的宝藏吧。

本来我打算等新博客全弄好了，再去通知你换一下你那里的友链，没想到这么快就被你发现了呀。

**Comment by CyrusYip** [comment]
> 我知道，原来的博客和底下的评论就当作是被我沉入海底的宝藏吧。

为啥呢？好可惜啊，有那么多精彩的交流。我之前给博客加英语语言会把评论弄不见，我还费心思把它们搬迁好了。

> 本来我打算等新博客全弄好了，再去通知你换一下你那里的友链，没想到这么快就被你发现了呀。

我在 GitHub 的 For you 栏目看到你新建了这个仓库，之前在统计之都看到你说申请 rbind.io 域名。那你可以弄好之后再叫我更新友链。

**Comment by CyrusYip** [comment]
加油！

**Comment by CyrusYip** [comment]
@yihui 谢谢。暂时不搬，需要再找你吧。我的 URL 不变应该挺好搬迁的。
